# Generated by Django 5.2.4 on 2025-08-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='job_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
