# Generated by Django 5.2.7 on 2025-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_cvupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='matching_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
