# Generated by Django 5.2.7 on 2025-12-15 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_cvupload_matching_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvupload',
            old_name='matching_score',
            new_name='job_match_score',
        ),
        migrations.RemoveField(
            model_name='cvupload',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='cvupload',
            name='job_name',
        ),
        migrations.AddField(
            model_name='cvupload',
            name='target_job_role',
            field=models.CharField(blank=True, help_text='Job role this CV was evaluated against', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cvupload',
            index=models.Index(fields=['uploaded_at'], name='analyzer_cv_uploade_b297f5_idx'),
        ),
        migrations.AddIndex(
            model_name='cvupload',
            index=models.Index(fields=['processed'], name='analyzer_cv_process_5e1d14_idx'),
        ),
        migrations.AddIndex(
            model_name='cvupload',
            index=models.Index(fields=['target_job_role'], name='analyzer_cv_target__a96a59_idx'),
        ),
    ]
